// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA2A0ErPnLHdpCVeT3v-BBBda_9xFXztCw',
    appId: '1:527956793081:web:2614be41ffebf47fa3f428',
    messagingSenderId: '527956793081',
    projectId: 'notes-app-ce721',
    authDomain: 'notes-app-ce721.firebaseapp.com',
    storageBucket: 'notes-app-ce721.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBYswgJEm1llxp0lZBWPBbPdBfeBsnf1Bw',
    appId: '1:527956793081:android:d43f2d3e7a349731a3f428',
    messagingSenderId: '527956793081',
    projectId: 'notes-app-ce721',
    storageBucket: 'notes-app-ce721.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD1lgwmka4b5hZ1YG6ChCh2zUtfmiOd6Uw',
    appId: '1:527956793081:ios:baa9b172988fe2c9a3f428',
    messagingSenderId: '527956793081',
    projectId: 'notes-app-ce721',
    storageBucket: 'notes-app-ce721.appspot.com',
    iosBundleId: 'com.example.notesAppFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD1lgwmka4b5hZ1YG6ChCh2zUtfmiOd6Uw',
    appId: '1:527956793081:ios:baa9b172988fe2c9a3f428',
    messagingSenderId: '527956793081',
    projectId: 'notes-app-ce721',
    storageBucket: 'notes-app-ce721.appspot.com',
    iosBundleId: 'com.example.notesAppFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA2A0ErPnLHdpCVeT3v-BBBda_9xFXztCw',
    appId: '1:527956793081:web:228fcae8c6ef1c5ba3f428',
    messagingSenderId: '527956793081',
    projectId: 'notes-app-ce721',
    authDomain: 'notes-app-ce721.firebaseapp.com',
    storageBucket: 'notes-app-ce721.appspot.com',
  );
}
